name: Execution Tests [Latest Anaconda, Linux]
on:
  schedule:
    # UTC 15:00 is early morning in Australia
    - cron:  '0 15 * * *'
jobs:
  execution-tests-linux:
    name: Execution Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install Anaconda + Dependencies
        shell: bash -l {0}
        run: |
          conda install anaconda
          pip install jupyter-book sphinx-multitoc-numbering quantecon-book-theme sphinxext-rediraffe sphinx-tojupyter sphinx-exercise sphinx-togglebutton
      - name: Build Lectures (+ Execution Checks)
        shell: bash -l {0}
        run: jb build lectures --path-output=./ -W --keep-going
      - name: Upload Execution Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: execution-reports
          path: _build/html/reports